// ignore_for_file: file_names, unnecessary_this, prefer_const_constructors, use_key_in_widget_constructors, no_logic_in_create_state, prefer_is_empty,  unnecessary_string_interpolations,  unnecessary_overrides, avoid_print, prefer_typing_uninitialized_variables, prefer_final_fields, sized_box_for_whitespace, deprecated_member_use, prefer_void_to_null, avoid_returning_null_for_void, constant_identifier_names, avoid_function_literals_in_foreach_calls, avoid_unnecessary_containers, prefer_adjacent_string_concatenation, prefer_if_null_operators, prefer_null_aware_operators
class SystemFlagNameList {
  String dateFormat;
  String accountCodePrefix;
  String accountCodeMaxLength;
  String productCodePrefix;
  String productCodeMaxLength;
  String invoiceNoPrefix;
  String invoiceNoMaxLength;
  String businessInventory;
  String introductionDone;
  String enableGoogleBackupRestore;
  String invoicePdfFooter;
  String paymentPdfFooter;
  String enableTax;
  String enableProductWiseTax;
  String decimalPlaces;
  String permissionsGranted;
  String askPinAlways;
  String termsAndCondition;
  String useProductSupplierCode;
  String enablePurchaseAndSupplierModule;
  String enableFingerPrint;
  String dbVersion;
  String salesReturnDays;
  String enableSalesReturn;
  String enablePurchaseReturn;
  String purchaseReturnDays;
  String showDashboardStatistics;
  String showSaleInvoicesSeprated;
  String showPurchaseInvoicesSeprated;
  String appLanguageCode;
  String defaultUnitCombination;
  String enableUnitModule;
  String financialMonth;
  String showSaleOrdersSeprated;
  String enableSaleOrder;
  String enableEmployee;
  String dbChanged;
  String referralId;
  String reminderPeriod;
  String notificationTime;
  String backUpTime;
  String lastContributedTime;
  String temp;
  String showSaleQuotesSeparated;
  String invoiceInitialNo;
  String saleQuoteInitialNo;
  String saleOrderInitialNo;
  String enableSalesQuote;
  String googleBackupEmail;

  SystemFlagNameList() {
    dateFormat = 'dateFormat';
    accountCodePrefix = 'accountCodePrefix';
    accountCodeMaxLength = 'accountCodeMaxLength';
    productCodePrefix = 'productCodePrefix';
    productCodeMaxLength = 'productCodeMaxLength';
    invoiceNoPrefix = 'invoiceNoPrefix';
    invoiceNoMaxLength = 'invoiceNoMaxLength';
    businessInventory = 'businessInventory';
    introductionDone = 'introductionDone';
    enableGoogleBackupRestore = 'enableGoogleBackupRestore';
    invoicePdfFooter = 'invoicePdfFooter';
    paymentPdfFooter = 'paymentPdfFooter';
    enableTax = 'enableTax';
    enableProductWiseTax = 'enableProductWiseTax';
    decimalPlaces = 'decimalPlaces';
    permissionsGranted = 'permissionsGranted';
    askPinAlways = 'askPinAlways';
    termsAndCondition = 'termsAndCondition';
    useProductSupplierCode = 'useProductSupplierCode';
    enablePurchaseAndSupplierModule = 'enablePurchaseAndSupplierModule';
    enableFingerPrint = 'enableFingerPrint';
    dbVersion = 'dbVersion';
    salesReturnDays = 'salesReturnDays';
    enableSalesReturn = 'enableSalesReturn';
    enablePurchaseReturn = 'enablePurchaseReturn';
    purchaseReturnDays = 'purchaseReturnDays';
    showDashboardStatistics = 'showDashboardStatistics';
    showSaleInvoicesSeprated = 'showSaleInvoicesSeprated';
    showPurchaseInvoicesSeprated = 'showPurchaseInvoicesSeprated';
    appLanguageCode = 'appLanguageCode';
    defaultUnitCombination = 'defaultUnitCombination';
    enableUnitModule = 'enableUnitModule';
    financialMonth = 'financialMonth';
    showSaleOrdersSeprated = 'showSaleOrdersSeprated';
    enableSaleOrder = 'enableSaleOrder';
    enableEmployee = 'enableEmployee';
    dbChanged = 'DB_CHANGED';
    referralId = 'REFERRAL_ID';
    reminderPeriod = 'REMINDER_PERIOD';
    notificationTime = 'NOTIFICATION_TIME';
    backUpTime = 'BACKUP_TIME';
    lastContributedTime = 'LAST_CONTRIBUTED_AT';
    temp = 'temp';
    showSaleQuotesSeparated = 'showSaleQuotesSeparated';
    invoiceInitialNo = 'invoiceInitialNo';
    saleQuoteInitialNo = 'saleQuoteInitialNo';
    saleQuoteInitialNo = 'saleQuoteInitialNo';
    saleOrderInitialNo = 'saleOrderInitialNo';
    googleBackupEmail = 'googleBackupEmail';
  }
}
